# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7b3862dab5d00e3c9366d19a0cd2d40d77eecb6740af4881db4b2117e1813ed1c5f267c2ca9466faf33d6d85576a437adb0a9b76942d956097e0a580f4bfba3

test:
  secret_key_base: 14c51f9e0d41f69d5673e55808dbe36c9d5af30ea1f64f6bc827c985a02905bb99bf2e542a54865391e78e3694f3e01e8eb59f9c021454c7c7ebbe97d1d545b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
